# See https://docs.docker.com/compose/compose-file/
version: "3.7"
services:
  postgres:
    container_name: cpsc304-db
    image: postgres:12.2
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cpsc304_dev

  web:
    container_name: cpsc304-web
    build:
      context: ./web
    depends_on:
      - postgres
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file: ./web/.env

volumes:
  db-data:
